from tvdatafeed import Interval

TELEGRAM_TOKEN = "7677308602:AAHH7vloPaQ7PqgFdBnJ2DKYy6sjJ5iqaYE"
TELEGRAM_CHANNEL = "@GokriptoHan"

SYMBOLS = ["BTCUSDT", "ETHUSDT", "SUIUSDT", "SOLUSDT", "AVAXUSDT"]
INTERVALS = [Interval.MIN_1, Interval.MIN_5]

BARS = 200
