TELEGRAM_TOKEN = "7677308602:AAHH7vloPaQ7PqgFdBnJ2DKYy6sjJ5iqaYE"
TELEGRAM_CHANNEL = "@GokriptoHan"

SYMBOLS = ["BTCUSDT", "ETHUSDT", "AVAXUSDT", "SOLUSDT", "SUIUSDT"]
INTERVALS = ["1m", "5m"]
TOLERANCE = 0.002
