services:
  - type: worker
    name: kripto-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python src/bot.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.5
      - key: TELEGRAM_TOKEN
        value: 7649989587:AAHUpzkXy3f6ZxoWmNTFUZxXF-XHuJ4DsUw
      - key: TV_USER
        value: marsticaret1
      - key: TV_PASS
        value: 8690Yn678690
